import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const html=readFileSync('public/rop-command-v2.html','utf-8');
const errors=[];
const dom=new JSDOM(html,{runScripts:'dangerously',beforeParse(w){w.addEventListener('error',e=>errors.push(e.message));}});
const d=dom.window.document;
const t=id=>d.getElementById(id)?.textContent?.trim()||'';
const has=(id,min=10)=>t(id).length>=min;
let fail=0;
const check=(name,ok)=>{console.log((ok?'OK  ':'FAIL')+' '+name);if(!ok)fail++;};
check('нет JS-ошибок при загрузке', errors.length===0);
if(errors.length)console.log('  errors:',errors.slice(0,3));
check('hero «Сегодня» наполнен', has('hero-today',50));
check('KPI-строка наполнена', has('kpi-today',50));
check('висящие сделки наполнены', has('zombie-card',50));
check('3 этапа наполнены', has('stages-gauges',50));
check('крупные сделки наполнены', has('hot-deals',30));
check('свежесть данных показана', t('freshTag').includes('снимок'));
dom.window.document.querySelector('#tabs button[data-s="team"]').click();
check('рейтинг менеджеров наполнен', has('scoreboard-card',100));
check('вис по менеджерам наполнен', has('team-zombie',30));
const row=d.querySelector('#scoreboard-card tr.mrow');
check('строка менеджера кликабельна', !!row);
if(row){row.click();
  check('страница менеджера открылась', d.getElementById('scr-manager').classList.contains('on'));
  const mc=t('mgr-content');
  check('июньский разбор сгенерирован', mc.includes('Разбор работы за июнь 2026'));
  check('разбор содержит цифры', mc.includes('Цифры июня'));
  check('контент менеджера объёмный', mc.length>500);
}
dom.window.document.querySelector('#tabs button[data-s="company"]').click();
check('воронка наполнена', has('funnel-card',100));
check('причины потерь наполнены', has('loss-reasons',50));
check('потери по менеджерам', has('loss-by-mgr',30));
check('план/факт наполнен', has('plan-fact',50) && t('plan-fact').includes('План'));
const btnAll=[...d.querySelectorAll('#period button')].find(b=>b.dataset.p==='all');
btnAll.click();
check('период «Всё» переключается', d.getElementById('periodLabel').textContent.length>5);
console.log(fail?`\nSMOKE FAIL: ${fail}`:'\nSMOKE PASS: все проверки зелёные');
process.exit(fail?1:0);
